/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief FTM2 channel 0 input capture source select: FTM2_CH0 signal */
#define SOPT4_FTM2CH0SRC_FTM 0x00u
/*!
 * @brief UART 1 transmit data source select: UART1_TX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u
/*!
 * @brief
 * FTM3 channel 0 output source: FTM3_CH0 pin is output of FTM3 channel 0 output modulated by FTM2 channel 1
 * output.
 */
#define SOPT8_FTM3OCH0SRC_FTM_MODULATED 0x01u

/*! @name PORTE1 (number 2), J2[20]/UART1_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA1 (number 23), J2[4]/RED_LED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LEDRGB_RED_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LEDRGB_RED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LEDRGB_RED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTD4 (number 61), J2[6]/SPI0_PCS1/LLWU_P14
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RF_CS_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RF_CS_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RF_CS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC1 (number 44), J24[6]/LLWU_P6/ADC0_SE15/PUSH_BUTTON2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW2_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC3 (number 46), J1[14]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CLKOUT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CLKOUT_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CLKOUT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CLKOUT_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CLKOUT_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
